sudo: false
dist: trusty

language: node_js
node_js:
- "10"

cache:
  directories:
  - "node_modules"

jobs:
  include:
  - stage: test
    name: test
    script: npm test
    if: branch != master
  - stage: test
    name: coverage
    script: npm run coveralls
    if: branch = master
  - stage: deploy
    name: npm
    script: npm run build
    deploy:
      provider: npm
      email: $NPM_EMAIL
      api_key: $NPM_TOKEN
      tag: latest
      on:
        tags: true
stages:
- test
- name: deploy
  if: tag IS present
